# Generated by Django 4.2.6 on 2023-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_otp_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp_attempt',
            field=models.IntegerField(default=3),
        ),
    ]
