# Generated by Django 4.2.6 on 2023-10-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_coupon_discount_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
