# Generated by Django 4.2.6 on 2023-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_address_options_orderplaced_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
