# Generated by Django 4.2.6 on 2023-11-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_address_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
