# Generated by Django 4.2.6 on 2023-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Outer Delivery', 'Outer Delivery'), ('Delivered', 'Delivered')], default='Confirmed', max_length=50),
        ),
    ]
