# Generated by Django 4.2.6 on 2023-11-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment',
            new_name='payment_mode',
        ),
    ]
