# Generated by Django 4.2.6 on 2023-11-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderplaced_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
    ]
