# Generated by Django 4.2.6 on 2023-11-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_orderplaced_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
