# Generated by Django 4.2.6 on 2023-12-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_comment_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='product',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
