# Generated by Django 4.2.6 on 2023-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_quote_quote_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='quantity',
            field=models.TextField(default=1),
        ),
    ]
