# Generated by Django 4.2.6 on 2023-12-23 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_orderplaced_options_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='delivered_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 12, 23, 7, 8, 17, 366057)),
            preserve_default=False,
        ),
    ]
