# Generated by Django 4.2.6 on 2023-12-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_orderplaced_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='delivered_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
